title: "Hagb 的小站"
author: Hagb (郭俊余)
email: hagb_green@qq.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  hagb
lang: zh_CN
minima:
  date_format: "%Y-%m-%d %H:%M"
  social_links:
    github: Hagb
    gitlab:
      username: Hagb
disqus:
  shortname: just_a_workaround
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
timezone: '+0800'
